[package]
name = "sycamorefmt"
version = "0.0.2"
edition = "2024"
description = "A code formatter for Sycamore's `view! { ... }` macro syntax, built on top of rustfmt."
license = "MIT"
repository = "https://github.com/sycamore-rs/sycamore"
keywords = ["sycamore", "formatter", "rustfmt", "view-macro"]
categories = ["command-line-utilities"]

[[bin]]
name = "sycamorefmt"
path = "src/main.rs"

[lib]
name = "sycamorefmt"
path = "src/lib.rs"

[dependencies]
clap = { version = "4.6", features = ["derive"] }
proc-macro2 = { version = "1.0.107", features = ["span-locations"] }
quote = "1.0.21"
syn = { version = "2.0", features = [
	"extra-traits",
	"full",
	"visit",
	"parsing",
	"printing",
] }
sycamore-view-parser = "0.9.2"

[dev-dependencies]
